### ISSUE TITLE
Don't use SSL encryption

### ISSUE THREAD

**Issue by hugomn** [miguel250/PostmarkBundle#13]
Why using https url as default? I'm having problems using SSL url in local environment. Thanks.

**Comment by miguel250** [comment]
I don't have time right now but if you like open a pull request adding  a new option to use https or not. https://github.com/miguel250/PostmarkBundle/blob/master/Postmark/Message.php#L328

**Comment by hugomn** [comment]
Thank you, @miguel250. I've made a fork and implemented it, and put it in a pull request. ;)
