### ISSUE TITLE
Add attachment with custom filename

### ISSUE THREAD

**Issue by mac-cain13** [miguel250/PostmarkBundle#15]
Sending an attachment now uses the filename as is from disk, it would be nice to have the possibility to tell the library what filename to use so you can customize the filename whenever desirable.

**Comment by miguel250** [comment]
Hey Mathijs I don't have time right now to make this change but if you like open a  pull request with some tests and I will merge.
—
Miguel Perez

**Comment by mac-cain13** [comment]
Maybe I have some time tonight or tomorrow to look into this and make a pull request to resolve this issue and #16.
