### ISSUE TITLE
Error: … not a valid entity or mapped super class.

### ISSUE THREAD

**Issue by sprain** [miguel250/PostmarkBundle#4]
Hi,
I am an experienced Postmark user and PHP developer, yet quite a newbie yet in Symfony2.

I installed everything according to your instructions and I get the following error when trying to send a message:
«Class Postmarkapp\PostmarkBundle\Services\Postmark is not a valid entity or mapped super class»

Any experiences with this or any hint on how to fix this?

Thanks!
Manuel

**Comment by miguel250** [comment]
Hey @sprain  how does your autoload.php look like?

**Comment by sprain** [comment]
Sorry for the late repsonse.
Unfortunately, Pull Request #5 has not solved the issue.

Interesting fact: I get the error but the email is being delivered as expected.

autoload.php looks right in my eyes:

```
$loader->registerNamespaces(array(
    'Symfony'          => array(__DIR__.'/../vendor/symfony/src', __DIR__.'/../vendor/bundles'),
    'Sensio'           => __DIR__.'/../vendor/bundles',
    'JMS'              => __DIR__.'/../vendor/bundles',
    'Doctrine\\Common' => __DIR__.'/../vendor/doctrine-common/lib',
    'Doctrine\\DBAL'   => __DIR__.'/../vendor/doctrine-dbal/lib',
    'Doctrine'         => __DIR__.'/../vendor/doctrine/lib',
    'Monolog'          => __DIR__.'/../vendor/monolog/src',
    'Assetic'          => __DIR__.'/../vendor/assetic/src',
    'Metadata'         => __DIR__.'/../vendor/metadata/src',
    'Postmark'         => __DIR__.'/../vendor',
    'Postmarkapp'      => __DIR__.'/../vendor/bundles',
    'Sprain'           => __DIR__.'/../vendor/bundles',
    'Knp\\Component'   => __DIR__.'/../vendor/knp-components/src',
    'Knp\\Bundle'      => __DIR__.'/../vendor/bundles',
));
```

**Comment by sprain** [comment]
Oops, my bad!
I used the same variable name twice which of course messed things up.
So the problem never really existed. Thanks for your assistance!
