### ISSUE TITLE
Add composer.json (also for postmark repo)

### ISSUE THREAD

**Issue by ruudk** [miguel250/PostmarkBundle#6]
Hi,

Symfony 2.1 RC1 is out and i'd love to test it out. Could you please add the composer.json file?

It's really simple. Something like this: https://raw.github.com/chrisboulton/php-resque/master/composer.json

You specify the miguel250/postmark.git dependency and register your repos on www.packagist.org.

http://packagist.org/about

**Comment by phidah** [comment]
+1

**Comment by miguel250** [comment]
I am starting to rewrite this bundle this week and when i am done I will add it to composer. I want to remove the dependency to https://github.com/Znarkus/postmark-php

**Comment by miguel250** [comment]
@ruudk and @phidah are you guys fine with this pull request #7?

**Comment by ruudk** [comment]
Sounds good to me, merge!

**Comment by phidah** [comment]
Looks good. Great job.

On 14/08/2012, at 09.45, Ruud Kamphuis notifications@github.com wrote:

Sounds good to me, merge!

—
Reply to this email directly or view it on
GitHubhttps://github.com/miguel250/PostmarkBundle/issues/6#issuecomment-7718631.
